### ISSUE TITLE
MN XDC/v1.0.0-unstable/linux Stopped Verifying - When will v1.1.4-stable be Available?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#10]
Hello Support - Sometime on Thursday, I believe something changed for MN processing and older versions are not verifying.  My XinFin-MN-PS node stopped working and is stuck in an endless loop every time I restart it.  It can not move forward in catching up on the block count to be current.

Has something changed that affects the MN processing?  when will the XDC/v1.1.4-stable/Linux version be available for everyone to use?

Thanks again for all of your support.
Preston

**Comment by shrikantgoswami** [comment]
This has been fixed.
