### ISSUE TITLE
Error: invalid receipt root hash 

### ISSUE THREAD

**Issue by mayong82** [XinFinOrg/XinFin-Node#135]
ERROR[06-28|09:59:55] 
########## BAD BLOCK #########
Chain config: {ChainID: 50 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: XDPoS}

Number: 76321136
Hash: 0xc28c3ff7a59ab49c4c4238ae7e059141b466093a36f8d9f8dabde7e252b8871c
        receipt{status=1 cgas=0 bloom=01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000 logs=[log: 0000000000000000000000000000000000000092 []  389a3ae0eecc4e6ed1604ed56e861aeee4f99d39311617b637f7638a772f0f26 0 c28c3ff7a59ab49c4c4238ae7e059141b466093a36f8d9f8dabde7e252b8871c 0]}
        receipt{status=1 cgas=6256645 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
        receipt{status=1 cgas=12513290 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
        receipt{status=1 cgas=18769935 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
        receipt{status=0 cgas=19384512 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
        receipt{status=1 cgas=19427947 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
        receipt{status=1 cgas=19427947 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[log: 0000000000000000000000000000000000000089 []  c9b6945c8d5e1e5e6bb260e2d8bb02f1699e59fd7cfb371bef467595e34b2d61 6 c28c3ff7a59ab49c4c4238ae7e059141b466093a36f8d9f8dabde7e252b8871c 1]}

Error: invalid receipt root hash (remote: 11c4ea28555ff59e1d083fb085df6df3f494aa062bf734fd4d3bd3fa45b0b380 local: 0b8250a6e3b23e2e594972afdc7fc2473a151ad11ee69abfb445924841716aca)
##############################

The node is out of sync. How to fix this issue  ???

**Comment by gzliudan** [comment]
What's your latest block number ?

**Comment by mayong82** [comment]
latest block number:  76321135

curl -s -X POST "http://127.0.0.1:8545" -H 'Content-type:application/json' --data '{ "jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id": 1 }'
{"jsonrpc":"2.0","id":1,"result":"0x48c916f"}

run docker node version:     xinfinorg/xinfinnetwork:v1.4.6

**Comment by gzliudan** [comment]
Please use the latest version.

**Comment by mayong82** [comment]
Upgraded to version xinfinorg/xdposchain:v1.6.0, currently in the process of block tracking .
