### ISSUE TITLE
Unable to setup masternode for windows

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XinFin-Node#14]
I have tried setting up masternode on windows, it is not working.

![image](https://user-images.githubusercontent.com/39384359/53715010-829e8280-3e76-11e9-8092-4c8dd505403e.png)

**Comment by shrikantgoswami** [comment]
Please note the last two warnings, it says that your system clock is off by -13m8.404939792s, any network (blockchain) that requires peer discovery & synchronization needs to have accurate date/time. Even 12 seconds fast can lead to failed discovery & synchronization.

If you open up the "Time and Date" settings app (just search for it from the start menu), there will be a radio button to set the time Automatically from the Internet. That should do it.

Link: https://www.tenforums.com/tutorials/6410-synchronize-clock-internet-time-server-windows-10-a.html
