### ISSUE TITLE
XDC Node not syncing further than Block 17099641

### ISSUE THREAD

**Issue by bmalepaty** [XinFinOrg/XinFin-Node#143]
I have set up the XDC Node using Method 2 (The Bootstrap Script)
This is .env file in mainnet directory:
`
INSTANCE_NAME=xdc_coinia
CONTACT_DETAILS=xyz@gmail.com
NODE_TYPE=full
NETWORK=mainnet
PRIVATE_KEY=3333333333333333333333333333333333333333333333333333333333333333
RPC_API=admin,db,eth,debug,miner,net,shh,txpool,personal,web3,XDPoS
`

This is the docker-compose.yml file:
`version: "3.4"

services:
  xinfinnetwork:
    image: xinfinorg/xdposchain:v1.6.0
    volumes:
      - "./xdcchain:/work/xdcchain"
      - "./genesis.json:/work/genesis.json"
      - "./start-node.sh:/work/start-node.sh"
      - "./bootnodes.list:/work/bootnodes.list"
      - "./.pwd:/work/.pwd"
      - "/etc/localtime:/etc/localtime:ro"
    restart: "always"
    env_file: .env
    ports:
      - "1332:30303"
      - "3332:8545"
      - "8888:8546"
`

These are the ERROR LOGS:
WARN [07-30|11:07:54] Full stats report failed                 err="ping timed out"
WARN [07-30|11:07:54] Failed to retrieve stats server message  err="read tcp 172.18.0.2:51618->45.82.64.150:3000: use of closed network connection"
WARN [07-30|11:08:04] Stats server unreachable                 err="dial tcp 45.82.64.150:3000: i/o timeout"
WARN [07-30|11:08:24] Stats server unreachable                 err="read tcp 172.18.0.2:48794->45.82.64.150:3000: i/o timeout"
WARN [07-30|11:08:44] Stats server unreachable                 err="dial tcp 45.82.64.150:3000: i/o timeout"
WARN [07-30|11:09:04] Stats server unreachable                 err="read tcp 172.18.0.2:35808->45.82.64.150:3000: i/o timeout"
WARN [07-30|11:09:24] Stats server unreachable                 err="dial tcp 45.82.64.150:3000: i/o timeout"
WARN [07-30|11:09:49] Initial stats report failed              err="ping timed out"
WARN [07-30|11:09:49] Failed to retrieve stats server message  err="read tcp 172.18.0.2:40364->45.82.64.150:3000: use of closed network connection"
WARN [07-30|11:09:59] Stats server unreachable                 err="dial tcp 45.82.64.150:3000: i/o timeout"
WARN [07-30|11:10:19] Stats server unreachable                 err="dial tcp 45.82.64.150:3000: i/o timeout"
WARN [07-30|11:10:39] Stats server unreachable                 err="read tcp 172.18.0.2:40252->45.82.64.150:3000: i/o timeout"
WARN [07-30|11:10:59] Stats server unreachable                 err="read tcp 172.18.0.2:40402->45.82.64.150:3000: i/o timeout"
WARN [07-30|11:11:19] Stats server unreachable                 err="read tcp 172.18.0.2:59138->45.82.64.150:3000: i/o timeout"
WARN [07-30|11:11:59] Full stats report failed                 err="ping timed out"
WARN [07-30|11:11:59] Failed to retrieve stats server message  err="read tcp 172.18.0.2:60292->45.82.64.150:3000: use of closed network connection"
WARN [07-30|11:12:09] Stats server unreachable                 err="dial tcp 45.82.64.150:3000: i/o timeout"
WARN [07-30|11:12:26] Stats server unreachable                 err="read tcp 172.18.0.2:60600->45.82.64.150:3000: i/o timeout"

**Can you please help if any changes are required here?**

**Comment by gzliudan** [comment]
please use below commands to start your node:

``bash
cd XinFin-Node/mainnet

# modify file .env
vi .env

./docker-up.sh
```

**Comment by bmalepaty** [comment]
@gzliudan I have tried that. Node was up and syncing, but only synced till block 17099641. Its almost a week, and not syncing any further.

**Comment by gzliudan** [comment]
You can use snapshot file to save time:

- full node: <https://download.xinfin.network/xdcchain.tar>
- archive node: <http://downloads.xinfin.network/xdcchain_archive.tar>

**Comment by bmalepaty** [comment]
@gzliudan Can you please help with more details on which folder path should the snapshot be unzipped/untarred

**Comment by gzliudan** [comment]
There is a directory named `XDC` under `XinFin-Node/mainnet/xdcchain`.

```bash
DATA_DIR="XinFin-Node/mainnet/xdcchain"
mv "${DATA_DIR}/XDC" "${DATA_DIR}/XDC.bak"
tar -xvf <SNAPSHOT_FILE> -C "${DATA_DIR}"
```

**Comment by bmalepaty** [comment]
Thank you @gzliudan 
We have downloaded the archive snapshot, and started unzipping using the above commands provided by you. But due to the size, the untar is taking a really long time.
Do you think we can abruptly stop the untar, and start the node using ./docker-up.sh, and let the node sync from there?

**Comment by bmalepaty** [comment]
@gzliudan We have gone ahead with the snapshot approach, and started the node using ./docker-up.sh.
But the node is still stuck at block 76468977 and not proceeding any further.

![image](https://github.com/user-attachments/assets/1f195155-c224-42fd-8ac1-1774632dc8ca)
These are the logs we see:
![image](https://github.com/user-attachments/assets/09e58ec7-0961-4bb3-bebe-9a9376974117)

**Comment by gzliudan** [comment]
You should has a public IP and expose the default port 30303.

**Comment by bmalepaty** [comment]
> You should has a public IP and expose the default port 30303.

30303 is already opened. Do you suggest any other ports to be open?
Also what is the frequency of snapshot. I see the snapshot you shared is upto June 25, 
When will the next snapshot be released?

**Comment by gzliudan** [comment]
`10.213.120.118` is a private IP. The other port is not used for sync.

**Comment by bmalepaty** [comment]
You are right. We are trying to set up XDC node for syncing and query archival node.
We have updated the docker-compose.yml to use that port (2332)
version: "3.4"

services:
xinfinnetwork:
image: xinfinorg/xdposchain:v1.6.0
volumes:
- "./xdcchain:/work/xdcchain"
- "./genesis.json:/work/genesis.json"
- "./start-node.sh:/work/start-node.sh"
- "./bootnodes.list:/work/bootnodes.list"
- "./.pwd:/work/.pwd"
- "/etc/localtime:/etc/localtime:ro"
restart: "always"
env_file: .env
ports:
- "1332:30303"
- "2332:8545"
- "8888:8546"

**Comment by bmalepaty** [comment]
Had to open a few more ports. Node is syncing now. Thank you for all the help
