### ISSUE TITLE
What KYC info required to "Become a Candidate"? (in MN Login)

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#15]
Hello Support - I now see that there is a "Become a Candidate" button at the top of the "MN Login" with the private key.  Sorry for not noticing this before.

Question (1) - What KYC info do I need to submit now testnet and what KYC is required later for the live XDC KYC?

Question (2) - I have not seen any way to link the running MN to the private key application.  The screen has not asked for my running MN name, IP address or rewards account.  Will this prompt come later after the KYC candidate?

Thank you again for your help!
I know everyone is working hard to get this up and running so I appreciate your time and support.

Preston

**Comment by shrikantgoswami** [comment]
Hello @presman, 

Answer (1) - We are working on finalizing the KYC requirements & it should be available on our website soon. 

> Every Node Holder needs to upload KYC document (Proof of identity (Individual and Corporate) and address duly notarized by the Notary Public) and this detail will be visible to the public network.

Link: https://docs.xinfin.org/docs/raw/masternodes

Answer (2) - You would be asked to provide your masternodes coinbase address when you apply to "Become a Candidate"

Regards
