### ISSUE TITLE
MN will not show in "Ordered list of masternode candidates"

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#16]
Hello Support Team - I am unable to get my Test Net MN to show up as a Candidate.  Can you provide guidance on how to fix this issue?  My MN is labeled "XinFin-MN-PS" and coinbase.txt file address begins with "0x1fb21f193xxxxxx".

Here is what I can view on my side:

(1) xdc.log file does not show my "0x1fb21f193xxxxx" address in the "Ordered list of masternode candidates or "New set of masternodes has been updated to snapshot ....... " list.  This is my public wallet #2 that was put into the coinbase.txt file to receive rewards.

(2) #MasterNode screen does not show my address as a MN Candidate "0x1fb21f193xxxx"

(3) #MasterNode Login screen application to become a candidate states:  "! This is not a candidate". -- This shows after entering PrivateKey wallet #1 with 10M Test XDC to lock, Upload PDF KYC document, entered my coinbase.txt address for wallet #2 "0x1fb21f193....." to receive rewards.

(4) MN named "XinFin-MN-PS" shows on the #Status screen as yellow, having only 2 nodes connected.

**Could you provide guidance on why my "XinFin-MN-PS" running MN will not show as qualified MN candidate?**

Note:  Sorry for all the prior questions that seem simple.  MEWconnect will not show me the private key needed here.  However, I discovered that I can create a keystore file and then open it with https://vintage.myetherwallet.com and use View Wallet Info to get the private key.

I have run the ./upgrade.sh to obtain the latest files.

I'm working through this process with limited documentation and I really appreciate your support and guidance.  Please let me know if there is anything I can do to help you with the MN Testing process.

Preston

**Comment by presman** [comment]
I performed a MN stop, upgrade and restart.  Afterwards, the XinFin-MN-PS node went from yellow to green.  I waited for the next checkpoint to pass.  I retried to "Become a Candidate" by entering private key with 10M test XDC, uploading KYC PDF and entering XDC address from coinbase.txt (wallet 2 for the rewards).

I then received the same error message that "This is not a candidate".

Can you help me to get past this error to become a MN candidate?

Thank you for your support!
Preston

**Comment by ronakgothi** [comment]
@presman We are looking in to your issue , once we are done with it we will get back to you.
Can you please share some console logs of the error.
Thank you

**Comment by presman** [comment]
Hello Support - Below is an example of the xdc.log file where the MN will list the new set of MN candidates.  However, it will not show my address from the coinbase.txt file.  Also, when I do the login to become a candidate, upload KYC document and then put in the coinbase.txt address  "0x1fb21f193....."  on your site, it shows me an error message "This is not a candidate".  Do you have any suggestions on why the "become a candidate" will not recognize the address and the xdc.log file will not show my node "XinFin-MN-PS" as a candidate?
-----------------------------------------------------------------------------------------------------------------
INFO [03-05|14:44:29] Imported new chain segment               blocks=1    txs=2    mgas=0.200   elapsed=3.730ms   mgasps=53.676  number=476549 hash=bcff71…68
72cd                                                      cache=202.77mB
INFO [03-05|14:44:31] Imported new chain segment               blocks=1    txs=8    mgas=0.651   elapsed=5.764ms   mgasps=112.955 number=476550 hash=3e314b…46
63e8                                                      cache=202.80mB
INFO [03-05|14:44:31] It's time to update new set of masternodes for the next epoch...
INFO [03-05|14:44:31] Ordered list of masternode candidates
INFO [03-05|14:44:31]                                          address=0x3Ea0A3555f9B1dE983572BfF6444aeb1899eC58C stake=10000000000000000000000000
INFO [03-05|14:44:31]                                          address=0x82D87b636DE6a4A706a2f434F43d9f39DB6bB42E stake=10000000000000000000000000
INFO [03-05|14:44:31]                                          address=0x942a5885A8844Ee5587C8AC5e371Fc39FFE61896 stake=10000000000000000000000000
INFO [03-05|14:44:31]                                          address=0x4F7900282F3d371d585ab1361205B0940aB1789C stake=10000000000000000000000000
INFO [03-05|14:44:31] Updating new set of masternodes
INFO [03-05|14:44:31] New set of masternodes has been updated to snapshot number=476550 hash=3e314b…4663e8
  new masternodes="[0x3Ea0A3555f9B1dE983572BfF6444aeb1899eC58C 0x82D87b636DE6a4A706a2f434F43d9f39DB6bB42E 0x942a5885A8844Ee5587C8AC5e371Fc39FFE61896 0x4F79002
82F3d371d585ab1361205B0940aB1789C]"
INFO [03-05|14:44:31] Masternodes are ready for the next epoch
INFO [03-05|14:44:33] Imported new chain segment               blocks=1    txs=4    mgas=0.341   elapsed=4.148ms   mgasps=82.130  number=476551 hash=a9e3ac…76
4b5a                                                      cache=202.81mB
INFO [03-05|14:44:35] Imported new chain segment               blocks=1    txs=5    mgas=0.418   elapsed=4.983ms   mgasps=83.958  number=476552 hash=3e7651…b7
e74d

**Comment by AnilChinchawale** [comment]
Hello,

You can propose Node in network as Block Producer Once Masternode Support xdc-addres prefix.
