### ISSUE TITLE
Several MNs stuck at 748,799; Explorer Down; Become Candidate Down

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#18]
Hello Support - There seems to be a disconnect to the Test XDC blockchain:

(1) Several MNs are stuck at 748,799 (see error log below) and have not worked in the green for 2 weeks

(2) Blockchain Testnet Explorer will not work; Error 502 Bad Gateway

(3) Masternode Become a Candidate will not work; It can not validate the 10M Test XDC value

Is there a code update or re-download that I need to perform to get my XinFin-MN-PS masternode running in the green again?

Do you have an estimate on when the next MN code upgrade will be available for download?

Note:  The system is still not recognizing my XinFin-MN-PS as a MN Candidate.

Thanks again for all of your support.  Please let me know if there is anything I can do to help with your testing.

Preston
--------------------------------------------------------------------------------------------------------
INFO [03-20|19:44:54] Imported new chain segment               blocks=419 txs=1675 mgas=142.681 elapsed=8.042s    mgasps=17.742 number=747463 hash=3483e4…04b230 cache=10.15mB
INFO [03-20|19:45:02] Imported new chain segment               blocks=412 txs=1657 mgas=140.703 elapsed=8.006s    mgasps=17.573 number=747875 hash=354b3b…ea8c97 cache=14.96mB
INFO [03-20|19:45:10] Imported new chain segment               blocks=475 txs=1904 mgas=162.194 elapsed=7.299s    mgasps=22.219 number=748350 hash=4b13be…3658ce cache=20.18mB
INFO [03-20|19:45:10] It's time to update new set of masternodes for the next epoch...
INFO [03-20|19:45:10] Ordered list of masternode candidates
INFO [03-20|19:45:10]                                          address=0x3Ea0A3555f9B1dE983572BfF6444aeb1899eC58C stake=10000000000000000000000000
INFO [03-20|19:45:10]                                          address=0x82D87b636DE6a4A706a2f434F43d9f39DB6bB42E stake=10000000000000000000000000
INFO [03-20|19:45:10]                                          address=0x942a5885A8844Ee5587C8AC5e371Fc39FFE61896 stake=10000000000000000000000000
INFO [03-20|19:45:10]                                          address=0x4F7900282F3d371d585ab1361205B0940aB1789C stake=10000000000000000000000000
INFO [03-20|19:45:10] Updating new set of masternodes
INFO [03-20|19:45:10] New set of masternodes has been updated to snapshot number=748799 hash=b97e33…2c16ee new masternodes="[0x3Ea0A3555f9B1dE983572BfF6444aeb1899eC58C 0x82D87b636DE6a4A706a2f434F43d9f39D
B6bB42E 0x942a5885A8844Ee5587C8AC5e371Fc39FFE61896 0x4F7900282F3d371d585ab1361205B0940aB1789C]"
INFO [03-20|19:45:10] Masternodes are ready for the next epoch
INFO [03-20|19:45:16] Imported new chain segment               blocks=391 txs=1563 mgas=133.143 elapsed=5.876s    mgasps=22.655 number=748741 hash=70ceb7…4cc17b cache=23.98mB
INFO [03-20|19:45:16] Imported new chain segment               blocks=58  txs=233  mgas=19.840  elapsed=849.113ms mgasps=23.365 number=748799 hash=b97e33…2c16ee cache=24.56mB
INFO [03-20|20:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-20|21:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-20|22:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-20|23:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|00:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|01:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|02:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|03:44:23] Regenerated local transaction journal    transactions=0 accounts=0
WARN [03-21|04:04:31] Full stats report failed                 err="ping timed out"
WARN [03-21|04:04:31] Failed to decode stats server message    err="read tcp 172.18.0.2:43818->109.169.40.125:3000: use of closed network connection"
INFO [03-21|04:44:23] Regenerated local transaction journal    transactions=0 accounts=0
WARN [03-21|05:00:10] Full stats report failed                 err="ping timed out"
WARN [03-21|05:00:10] Failed to decode stats server message    err="read tcp 172.18.0.2:45772->109.169.40.125:3000: use of closed network connection"
INFO [03-21|05:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|06:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|07:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|08:44:23] Regenerated local transaction journal    transactions=0 accounts=0
INFO [03-21|09:44:23] Regenerated local transaction journal    transactions=0 accounts=0

**Comment by presman** [comment]
Hello Support - Do you have an estimate on when the new MN code will be available to download and upgrade?  My testnet MN has been down for several weeks after changes on your hosting side.  My MN names "XinFin-MN-PS" will not even show in the list because it fails to get a connection. (error is use of closed network connection)

Thanks for your help!
Preston

**Comment by AnilChinchawale** [comment]
Above issue fixed with latest #21, Hence closing issue.
