### ISSUE TITLE
My MN no longer appears in running list after latest changes

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#19]
Hello Support - After the latest host changes on your side, my MN labeled "XinFin-MN-PS" no longer appears in your list at all and gets errors in the log file trying to connect.

Could you please advise on what I need to change to incorporate the latest setup changes so it is running green on the testnet?

Thank you again for all your help!
Preston

**Comment by presman** [comment]
Here is the xdc.log file error message that just keeps repeating.  It started after changes were made on the XinFin host / lockchain side.

What do I need to do to fix the problem and get my testnet MN running back in green as it should?

Thanks again for your support.
Preston
------------------------------------------------------------------------------------
WARN [03-26|12:30:13] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:30:23] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:30:33] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:30:43] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:30:53] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:31:03] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:31:13] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:31:23] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:31:33] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:31:43] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-26|12:31:53] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"

**Comment by ronakgothi** [comment]
we will have a look and get back to you

**Comment by presman** [comment]
Hello Support - It seems as if my "XinFin-MN-PS" MN server is connected to an older blockchain and your new testnet servers are running on a new blockchain.  The block counts are different and I am unable to connect to the stats server, etc.  I have tried the upgrade.sh with no improvements seen.  Also, the download MN code has not been updated in 26 days.

Could you please provide me with the updated code or changes so that I can get my MN running correctly again and in sync with your testnet?

Thank you again for your help!
Preston 

Here is the current error log:
---------------------------------------------------------------------------------
INFO [03-30|14:03:56] Block synchronisation started
WARN [03-30|14:03:56] Stats server unreachable                 err="websocket.Di                                                                                                                                   al ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xi                                                                                                                                   nfin.network on 127.0.0.11:53: no such host"
INFO [03-30|14:03:59] Imported new chain segment               blocks=2 txs=11 m                                                                                                                                   gas=0.915 elapsed=186.647ms mgasps=4.900 number=727245 hash=522c11…20a069 cache=                                                                                                                                   84.53kB
INFO [03-30|14:03:59] Imported new chain segment               blocks=1 txs=0  m                                                                                                                                   gas=0.000 elapsed=1.158ms   mgasps=0.000 number=727246 hash=58f758…9f60aa cache=                                                                                                                                   84.53kB
INFO [03-30|14:03:59] Imported new chain segment               blocks=3 txs=12 m                                                                                                                                   gas=1.022 elapsed=52.906ms  mgasps=19.322 number=727249 hash=89867a…353ced cache                                                                                                                                   =176.79kB
INFO [03-30|14:03:59] Imported new chain segment               blocks=5 txs=24 m                                                                                                                                   gas=2.044 elapsed=70.904ms  mgasps=28.831 number=727254 hash=1b0483…a3516c cache                                                                                                                                   =365.63kB
INFO [03-30|14:04:00] Imported new chain segment               blocks=14 txs=53                                                                                                                                    mgas=4.537 elapsed=163.400ms mgasps=27.767 number=727268 hash=9bc9aa…961999 cach                                                                                                                                   e=787.72kB
INFO [03-30|14:04:00] Imported new chain segment               blocks=33 txs=133                                                                                                                                    mgas=11.321 elapsed=371.979ms mgasps=30.434 number=727301 hash=54a0fa…c136c4 ca                                                                                                                                   che=1.83mB
INFO [03-30|14:04:01] Imported new chain segment               blocks=71 txs=283                                                                                                                                    mgas=24.112 elapsed=1.024s    mgasps=23.532 number=727372 hash=a2ab93…df6165 ca                                                                                                                                   che=4.08mB
WARN [03-30|14:04:07] Stats server unreachable                 err="websocket.Di                                                                                                                                   al ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xi                                                                                                                                   nfin.network on 127.0.0.11:53: no such host"

**Comment by presman** [comment]
I removed the XinFin-Node folder, reinstalled everything, setup the ENV and coinbase.txt file.  This did not fix the problems.  It appears that I am running against an older testnet blockchain using the v1.0.0-unstable code.  All current running testnet MNs are on the 0.5-stable code.

Could you provide an update of the code for download so I can continue participating in the testnet program?

Thank You
Preston

**Comment by presman** [comment]
Hello Support Team - I am still getting the same error message below in the xdc.log file that the Stats server is unreachable.

Please provide some guidance on how to resolve the issue or updated code to download.
Thank you for your help!
Preston
-----------------------------------------------------------------
WARN [03-31|20:56:47] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-31|20:56:57] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-31|20:57:07] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [03-31|20:57:17] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"

**Comment by presman** [comment]
Hello Support Team - My master node "XinFin-MN-PS" is still down and getting the following errors below that the testnet stats server is unreachable.  I MN does not show in the running list after the testnet changes a couple of weeks ago.  I am running on Linux and the upgrade.sh indicates I have the latest image.

Please provide guidance on how to resolve the issue or provide updated code to download.

Thank you for your help!
Preston

--------------------------------------------------
WARN [04-04|01:06:10] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [04-04|01:06:20] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [04-04|01:06:30] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"
WARN [04-04|01:06:40] Stats server unreachable                 err="websocket.Dial ws://stats.testnet.xinfin.network:3000/api: dial tcp: lookup stats.testnet.xinfin.network on 127.0.0.11:53: no such host"

**Comment by AnilChinchawale** [comment]
Above issue fixed with latest #21, Hence closing issue.
