### ISSUE TITLE
ERROR Bootstrap URL invalid for enode= err=invalid URL schedme, want enode

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#22]
Hello Team - Thank you for updating the MN source code.  I removed my old folders and re-installed a fresh copy of the code.  I updated the .env file.  When I start running on Ubuntu Linux, the block count rises to around 30K and then resets back to 1, over and over.  My MN shows in your Stats list now as "XinFin-MN-PS"

The error that shows before the reset is related to Bootstrap URL invalid for enode=.  The error log is listed below.

Could you provide guidance on how to fix this?
Thank you!
Preston

-----------------------------------------------------------------------------------
INFO [04-05|15:32:31] Imported new chain segment               blocks=145 txs=437  mgas=38.297  elapsed=500.482ms mgasps=76.520  number=2845  hash=8b7b39…c4773c cache=6.50mB
INFO [04-05|15:32:32] Imported new chain segment               blocks=305 txs=915  mgas=80.168  elapsed=955.671ms mgasps=83.887  number=3150  hash=36474e…c0b8c7 cache=7.04mB
INFO [04-05|15:32:32] It's time to update new set of masternodes for the next epoch...
INFO [04-05|15:32:32] Ordered list of masternode candidates
INFO [04-05|15:32:32]                                          address=xdc942a5885A8844Ee5587C8AC5e371Fc39FFE61896 stake=50000000000000000000000
INFO [04-05|15:32:32]                                          address=xdc4F7900282F3d371d585ab1361205B0940aB1789C stake=50000000000000000000000
INFO [04-05|15:32:32]                                          address=xdc3Ea0A3555f9B1dE983572BfF6444aeb1899eC58C stake=50000000000000000000000
INFO [04-05|15:32:32] Updating new set of masternodes
INFO [04-05|15:32:32] New set of masternodes has been updated to snapshot number=69857 hash=b99f4f…56e7cd new masternodes="[xdc942a5885A8844Ee5587C8AC5e371Fc39FFE61896 xdc4F7900282F3d371d585ab1361205B0940aB1789C
 xdc3Ea0A3555f9B1dE983572BfF6444aeb1899eC58C]"
INFO [04-05|15:32:32] Masternodes are ready for the next epoch
INFO [04-05|15:32:33] Imported new chain segment               blocks=79  txs=237  mgas=20.764  elapsed=269.657ms mgasps=77.003  number=3229  hash=808ca3…8bc07e cache=7.18mB
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:243 +0x143
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# [select]:
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:196 +0x117
ERROR[04-05|15:32:13] Bootstrap URL invalid                    enode= err="invalid URL scheme, want \"enode\""
ERROR[04-05|15:32:13] Bootstrap URL invalid                    enode= err="invalid URL scheme, want \"enode\""
INFO [04-05|15:32:13] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-05|15:32:13] Starting peer-to-peer node               instance=XDC/v0.5.0-stable/linux-amd64/go1.11.6
INFO [04-05|15:32:13] Allocated cache and file handles         database=/work/xdcchain/XDC/chaindata cache=768 handles=1024
INFO [04-05|15:32:14] Initialised chain configuration          config="{ChainID: 1151 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: XDPoS}"
INFO [04-05|15:32:14] Initialising Ethereum protocol           versions="[63 62]" network=1151
WARN [04-05|15:32:14] Head state missing, repairing chain      number=30054 hash=cde6bc…ecb1ee
INFO [04-05|15:32:16] Rewound blockchain to past state         number=2     hash=b60948…3489ab
INFO [04-05|15:32:16] Loaded most recent local header          number=69857 hash=b99f4f…56e7cd td=209571
[select]:: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc00402f560)
-bash: syntax error near unexpected token `*Peer'
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain#         /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:243 +0x143
-bash: /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:243: No such file or directory
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
-bash: syntax error near unexpected token `('
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain#         /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:196 +0x117
-bash: /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:196: No such file or directory
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# ERROR[04-05|15:32:13] Bootstrap URL invalid                    enode= err="invalid URL scheme, want \"enode\""
ERROR[04-05|15:32:13]: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# ERROR[04-05|15:32:13] Bootstrap URL invalid                    enode= err="invalid URL scheme, want \"enode\""
ERROR[04-05|15:32:13]: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# INFO [04-05|15:32:13] Maximum peer count                       ETH=25 LES=0 total=25
INFO: command not found
15:32:13]: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# INFO [04-05|15:32:13] Starting peer-to-peer node               instance=XDC/v0.5.0-stable/linux-amd64/go1.11.6
15:32:13]: command not found
INFO: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# INFO [04-05|15:32:13] Allocated cache and file handles         database=/work/xdcchain/XDC/chaindata cache=768 handles=1024
INFO: command not found
15:32:13]: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# INFO [04-05|15:32:14] Initialised chain configuration          config="{ChainID: 1151 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: XDPoS}"
INFO: command not found
15:32:14]: command not found
root@XinFin-MasterNode-PS:/XinFin-Node/xdcchain# INFO [04-05|15:32:14] Initialising Ethereum protocol           versions="[63 62]" network=1151
INFO: command not found

**Comment by AnilChinchawale** [comment]
Hello,

Fixed raise issue in latest PR i.e. #23 .
Please fetch latest code from github and restart node.
