### ISSUE TITLE
Web Wallet Address Upper vs Lower Case (Which is Right?)

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#28]
Hello Team - The new Web Wallet is creating addresses with xdc.... prefix.  However, it displays two different public addresses.  Which is correct?

(1) Open wallet.
(2) Upper left wallet address displayed has upper and lower case letters mixed in the address.  When using Copy, it also copies with upper and lower case letters.  Here is the TestNet public address I see:
	xdcf9c0751492aAE97E9F442Af212960558370C5D1E
(3) Click Print under the address to view the private key.  On this pop-up screen, the public address is displayed as follows in all lower case:
	xdcf9c0751492aae97e9f442af212960558370c5d1e

Preston Stroud

**Comment by AnilChinchawale** [comment]
Please note that there is no case senstive in XDC public address, hence you can use both case.
