### ISSUE TITLE
Docker Install does not work with Ubuntu 19.04

### ISSUE THREAD

**Issue by CryptosAndTokens** [XinFinOrg/XinFin-Node#33]
Docker partially installs, but does not execute when you execute: sudo docker-compose -f docker-services.yml up -d command.

**Comment by CryptosAndTokens** [comment]
Incompatible, see link: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by CryptosAndTokens** [comment]
root@vultr:~/xinfin-node# ERROR: Couldn't connect to Docker daemon. You might need to install Docker:
>
>https://docs.docker.com/engine/installation/
> root@vultr:~/xinfin-node# sudo docker-compose -f docker-services.yml up -d

**Comment by AnilChinchawale** [comment]
Can you share logs to debug issue.

**Comment by Sassh79** [comment]
That work for me on Ubuntu 19.04
sudo apt install docker.io

**Comment by presman** [comment]
I had same issue recently with Ubuntu 19 and had to install docker_compose and docker.io for the node to run
