### ISSUE TITLE
Apothem - Linux One-Click Install .rar contins .EXE?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#34]
Hello Team - I downloaded the Linux .RAR file to my Ubuntu Linux server and unpacked it.  The file contains a .EXE file that will not run on the Ubuntu Linux server.

Can you help?

Preston Stroud

**Comment by presman** [comment]
Note:  All 3 One-Click installer links for Windows, Linux and MacOS are pointing to the exact same file/link.

**Comment by AnilChinchawale** [comment]
Windows and Linux Application are available on URL :- https://xinfin.org/setup-masternode.php
