### ISSUE TITLE
One-Click - Create New Account - Locks up

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#36]
When running the One-click  XinFin-Network program on a Windows 2016 server, it immediately syncs with the Apothem network and updates the block count.  It shows in the #stats correctly.

However, It states that a new account is needed.  When I Create Account, it shows "GENERATING ACCOUNT" on the screen and never goes away and never generates an account.

Preston Stroud

**Comment by presman** [comment]
In my Windows 2016 Test Server, I ran update and it states I have the latest version.  I can also see the server running in the #stats with generic name "XinFin-Test-Network-One-Click (155.138.214.251)
Issues:
(1) When I go to Add Account to enter password, it shows "GENERATING ACCOUNT" and just locks up there.
(2) I can not find a place to change the node name
(3) I can not find a place to enter the coinbase.txt address or rewards address file, that links it to the private key candidate with 10M locked

Preston Stroud

**Comment by AnilChinchawale** [comment]
Fixed in latest release.
