### ISSUE TITLE
One-Click - Where does Rewards coinbase.txt address go on Windows?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#37]
The Master Node candidate registration requires the MN server's rewards address from the coinbase.txt file.  However, I can not find this in a file search of the new Windows One-Click installation on a new Windows 2016 server.  Where do we put this address on the new one-click server and how do we change the server name?

Thank You
Preston Stroud

**Comment by AnilChinchawale** [comment]
Public address are visible in Latest release of application.
