### ISSUE TITLE
MN Test XDC Wallet

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#4]
I am setting up a XinFin master node.  It is 90% complete and I just need 2 issues addressed.
I created a new WebWallet as a keystore file to hold the Test XDC.  The transfer Test XDC said it was successful.  However, it is not in the wallet or blockchain scan.  The keystore wallet only shows XDCE as an option and not XDC.

Please help.  What wallet do I use to hold Test XDC?

Where do I place this wallet address on the server or how to I upload the keystore file from Windows to Linux?

Thank you!
Preston

**Comment by presman** [comment]
I have tried this from Chrome and Windows Edge.  Both give me the following error message on trying to transfer the 10M tokens to my 0xDxxxxxxxxx public filestore wallet address:
{"error":{"message":"known transaction: f307c20acb4fde5b7554ce7be7f55acd6999b7e6d83e76fbf7f5d5d256ce8226"}}

**Comment by presman** [comment]
I tried the other wallet type with 12 keywords and it is only ERC20 or XDCE based as well.  It does not hold XDC (or testnet XDC).  I can not create a new XDC ewallet because it wants my email and phone number, that are tied to my LIVE XDC tokens.  Shouldn't we be using separate XDC wallets to store LIVE XDC verses TEST XDC?  How do I get a TestXDC wallet for the master node?

**Comment by shrikantgoswami** [comment]
Please try creating a new wallet here http://xinfin.network/#webWallet  (MEWconnect - recommended method) & use this wallet address to get the 10M test XDC. You can then login using the same webWallet link with a QR code that MEWConnect app provides. To see your 10M testnet XDC please "change" the Network to XinFin.Network (XDC)
