### ISSUE TITLE
Apothem Block Explorer - Shows Wrong total

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#40]
The block explorer shows 11M TestXDC tokens transferred to my public address and shows the transaction.

However, at the top, for the total XDC, it only shows 1,999,999 as the amount available.  Where did the rest go?  Was it locked for the master node?

There is no way to see what is locked, what is voting and what is available.
Use Block Explorer on this address to see:  xdc111aE47639435eA5fF9619682d4e60cb3e3369b8

Preston

**Comment by parmarrushabh** [comment]
You have proposed for the master node so your 10 million xdc tokens are locked and rest of the xdc were used as a gas price for uploading your kyc
