### ISSUE TITLE
Masternode coinbase address?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#5]
The masternode installation created a coinbase file to hold an address.

What is this address needed for?

What format?  BTC, BCH, ETH, LTC?

Thank you!
Preston

**Comment by shrikantgoswami** [comment]
The coinbase address is the public key of the account that your masternode is using. This address will be required when you need to apply to become a masternode http://xinfin.network/#masternode

Format will be XDC.

**Comment by presman** [comment]
So just to confirm, I am to put my “real” XDC Wallet Address with the real live 10M XDC tokens.  Put that address into the Coinbase file so you guys can verify that I really have the 10M XDC live? Right?

 

Thanks again for your help!

Preston Stroud

**Comment by shrikantgoswami** [comment]
You can create a new wallet http://xinfin.network/#webWallet to receive the 10M test XDC. You don't need to put that address in the coinbase file. You need to have two separate wallets. One is coinbase (public) for your node & the other one is private from where you will need to deposit the 10M XDC & receive rewards. You will need the coinbase address from the text file when you want to apply as a masternode http://xinfin.network/#masternode
