### ISSUE TITLE
New Masternode does not show:  XinFin-MN-PS

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#6]
I have a new XinFin MasterNode up and running on Linux.  I can see the Xinfin process running.  I put my "LIVE" XDC wallet address in the coinbase.txt file.  I have my name and email in the .env file.

I still do not have a test XDC wallet with the 10M test tokens.  I also do not know where to put the test XDC wallet address after I get it.  Can you provide guidance?  The IP address is  149.28.237.122 with masternode ID:  XinFin-MN-PS

Per the other issue above, the keystore file only holds XDCE and not XDC for some reason......

Thanks for your help!
Preston

**Comment by presman** [comment]
I am now showing on the network stats list as unstable but running now.  Can you help identify the problem and how to get a test XDC wallet (separate from my live wallet) that holds test XDC?  Where does it go when I get it?
Thank you!
Preston

**Comment by shrikantgoswami** [comment]
Please note you need to have two separate wallets. One is coinbase (public) for your node & the other one is private from where you will need to deposit the 10M XDC & receive rewards. Once you have 10M XDC in your private wallet, you need to login here http://xinfin.network/#masternode using your private wallet key/MNEMONIC. Then you provide your node's coinbase address from the (coinbase.txt ) along with 10M XDC stake to apply as a masternode.

**Comment by presman** [comment]
OK, I think I understand now what you are saying:

TEST XDC MasterNode - Need (2) Wallets:
(1) Need a Public wallet (put address in coinbase.txt file) to receive Test XDC staking rewards (Not Locked)
(2) Need another Private wallet (register #masternode TestNet) where 10M Test XDC are Locked for 30 days while staking

REAL LIVE XDC MasterNode - Need (2) Wallets:
(1) Need a Public wallet (put address in coinbase.txt file) to receive Real Live XDC staking rewards (Not Locked)
(2) Need a Private wallet (register #masternode LiveNet) where 10M Real Live XDC are Locked for 30 days while staking

Is this correct?

Thank you again for your support.,
Preston
