### ISSUE TITLE
how to monitor the node?

### ISSUE THREAD

**Issue by Ivanello** [XinFinOrg/XinFin-Node#60]
Guys help please wit 2 question, 
1. how to monitor node from inside? do You have option to export metrics somehow 
I found key --metrics in XDC but dont know how it working
2. how to monitor or at least get status from outside, make some http request or other way? 

thanks a lot!

**Comment by AnilChinchawale** [comment]
Currently, we can monitor Node information using XDCStats at xinfin.network.

Kindly share us reference if you need any specific tools which currently available in geth ecosystem.
