### ISSUE TITLE
can not sync blockdata

### ISSUE THREAD

**Issue by qlfgggggg** [XinFinOrg/XinFin-Node#66]
![image](https://user-images.githubusercontent.com/43543840/152980585-8610be5a-0233-4813-a10d-d5e1e7485e23.png)

**Comment by qlfgggggg** [comment]
![image](https://user-images.githubusercontent.com/43543840/153192487-2d69e7d4-503e-4eb1-9cb9-19e9f59f63d1.png)

**Comment by AnilChinchawale** [comment]
Kindly find below the steps for setting up Mainnet XDC Node using a snapshot.


`
sudo docker-compose -f docker-services.yml down

wget https://download.xinfin.network/xdcchain.tar

tar -xvzf xdcchain.tar

mv xdcchain/XDC xdcchain/XDC_old

mv XDC xdcchain

bash upgrade.sh
`
