### ISSUE TITLE
How to get (2) XDC compatible wallets (live & test)?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#7]
I'm sorry for being difficult here but I have tried all options provided and I am still unable to get (2) different XDC wallets, one for my LIVE XDC and one for the TEST XDC:

LIVE XDC
(1) Android XDCWallet - holds my LIVE XDC tokens
(2) eWallet - at XinFin website also shows my same LIVE XDC tokens

TEST XDC
(3) MEWconnect - only supports ERC20 or XDCE (not XDC)
(4) Keystore wallet - only supports ERC20 or XDCE (not XDC)
(5) Mnemonic Phrase wallet - only supports ERC20 or XDCE (not XDC)

Please help me to get a second dummy wallet for the TEST XDC to be held in!!!!!  I can't find a way to get a second XDC wallet to use for TEST XDC tokens.

Based on your instructions, once I have a TEST XDC wallet, I put this in the coinbase.txt file.  Then I log into the masternode website and link this TEST XDC coinbase.txt wallet to my LIVE XDC wallet to stake them and apply as a master node.

Thank you again for your patience and help.
Preston

**Comment by presman** [comment]
I used the MEWconnect and transferred 10M Test XDC.  The transaction number in the explorer  shows it transferred but they do not show in the MEWconnect, because it looks like it only supports erc20 tokens???

Where do I put this MEWconnect address on the masternode?  In the coinbase.txt file???

**Comment by ronakgothi** [comment]
Please select network as xinfin network ,you can find the XDC compatibility there.
