### ISSUE TITLE
Masternode login screen - Needs Private Key?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#8]
Hello Support - I am unable to login to the "create a masternode" screen.  It wants a PrivateKey for the login / setup.

Is this the TEST XDC Wallet or LIVE XDC Wallet Private Key?

Also, I am unable to obtain the private keys.  I have looked on XDCWallet online, Android XDC wallet, MEWconnect, keystore wallet and can not find the private key.  

I just have access to the keystore wallet files or seed words and the public keys.

Thank you again for your help and patience.
Preston

**Comment by presman** [comment]
Please note this screen is asking for a private key on an unsecured screen.  It does not have https://

**Comment by ronakgothi** [comment]
> Hello Support - I am unable to login to the "create a masternode" screen. It wants a PrivateKey for the login / setup.
> 
> Is this the TEST XDC Wallet or LIVE XDC Wallet Private Key?
> 
> Also, I am unable to obtain the private keys. I have looked on XDCWallet online, Android XDC wallet, MEWconnect, keystore wallet and can not find the private key.
> 
> I just have access to the keystore wallet files or seed words and the public keys.
> 
> Thank you again for your help and patience.
> Preston

Please access your wallet using ur keystore and there u can view your wallet info there u can find your private key as well.

**Comment by presman** [comment]
Note for others:  Open the wallet with WebWallet on XinFin.network site so it has the correct network to support XDC blockchain.  Once the wallet is open, select the printer icon under the wallet address upper left.  The printer icon pops up a page that shows the public and private address.

This is how to get the private key that is needed to register for MN candidate.

Preston
