### ISSUE TITLE
 Masternode setup for windows

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XinFin-Node#9]
I am unable to setup masternode for windows, got stuck here refer below image @shrikantgoswami 

![xinfinnode1](https://user-images.githubusercontent.com/39384359/53571013-d6b31980-3b8d-11e9-9b90-8347f68df264.PNG)

**Comment by shrikantgoswami** [comment]
Can you try with the xdc-start.bat script as an administrator, it should be in Program Files x86/XinFin-Node directory.

**Comment by shrikantgoswami** [comment]
Fixed, try with the new installer & it should work.
